import Head from 'next/head';
import Image from 'next/image';

export default function Info() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
        <div className="container m-auto">
            
                <div className='text-center'>
                    <div className=" m-5 border-2 border-indigo-600 rounded-lg flex justify-center">
                        <div className="max-w-10">
                            <h1 className="font-bold text-2xl place-self-center text-gray-800">
                                <h3> Маньяма Тумайн Маньяма</h3>
                            </h1>
                            <p className="text-gray-600">
                                <h4 class="font-semibold">НГТУ -  20-РТ, ИПТМ</h4>
                                <p>Python, pandas, numpy, matplotlib, opencv, tkinter</p>
                            </p>
                            
                        </div>
                    </div>
                </div>
                <div className='text-center'>
                    <div className="m-5 border-2 border-indigo-600 rounded-lg flex justify-center">
                        <div className="max-w-10">
                            <h1 className="font-bold text-center text-2xl text-gray-800">
                                <h3>Массунда Жуниор Фернандо Эрнешто</h3>
                            </h1>
                            <p className="text-gray-600">
                                <h4 class="font-semibold">НГТУ -  20-РТ, ИПТМ</h4>
                                <p>Python, ML</p>
                            </p>
                            
                        </div>
                        <p className="text-gray-600">
                            <h4></h4>
                        </p>
                    </div>
                </div>
                <div className='text-center'>
                    <div className="m-5 border-2 border-indigo-600 rounded-lg  flex justify-center ">
                        <div className="max-w-10">
                            <h1 className="font-bold text-2xl text-center text-gray-800">
                                <h3>Абубакар Каба </h3>
                            </h1>
                            <p className="text-gray-600">
                                <h4 class="font-semibold">НГТУ - 20-ИС, ИРИТ</h4>
                                <p>Python, MySQL, JavaScript, React JS, Next JS, Bootstrap, Tailwiind, c++</p>
                            </p>
                            
                        </div>
                    </div>
                </div>
                <div className='text-center'>
                    <div className="m-5 border-2 border-indigo-600 rounded-lg  flex justify-center ">
                        <div className="max-w-10">
                            <h1 className="font-bold text-2xl text-gray-800">
                                <h3>Раймунду Инасиу</h3>
                            </h1>
                            <p className="text-gray-600">
                                <h4 class="font-semibold">НГТУ - 20-ИС, ИРИТ</h4>
                                <p>JavaScript, React JS, Typescript, Next.js, Computer Science Student, SQL</p>
                            </p>
                            
                        </div>
                    </div>
                </div>
                <div className='text-center'>
                    <div className="m-5 border-2 border-indigo-600 rounded-lg  flex justify-center ">
                        <div className="max-w-10">
                            <h1 className="font-bold text-2xl text-gray-800">
                                <h3>Жозе Жоау Петерсон Дикала</h3>
                            </h1>
                            <p className="text-gray-600">
                                <h4 class="font-semibold">НГТУ -  20-ИС, ИРИТ</h4>
                                <p>Python, C++, MySQL, HTML, CSS, JavaScript</p>
                            </p>

                        </div>
                    </div>
                </div>
        </div>
      </main>
    </>
  );
}